[build]
publish = "packages/client/build"
command = "yarn build"

[dev]
command = "yarn run dev"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
